### PR TITLE
Improvements to publishing script

### PR DESCRIPTION
**Pull request by dsingleton**
**Background**

This repo hasn't been staying in sync with changes from FET. Previous discussion: https://github.com/alphagov/govuk_frontend_toolkit_npm/pull/15

**Problems**

1. *Deletion*: This repo contains files removed from FET. These are also included the code published to `npm`. It _shouldn't_ have broken the package for users, but could cause confusion where files that have deprecated/removed are still in the package.
2. *Addition*: This repo is missing files added to FET, that _are_ included in the code published to `npm`, but are not reflected in the commits here.

**Changes**

- The changes to `npmignore` aren't directly related, but also make the publish process a little more explicit about what we want to publish.

- The second commit does the bulk of the work. Using `rsync --delete` ensures files removed from FET are removed from the local file system. Using `git add --all` ensures deleted files are removed from the git index, it also ensures new files are added. 

- I found the `git commit` / `npm version` / `git reset` / `git commit` dance difficult to follow, so i've tried to simplify it for the next person.

**Output**

This branch shows the output of manually running the new `publish.sh` script: 
https://github.com/alphagov/govuk_frontend_toolkit_npm/compare/simpler-publish-script...simpler-publish-script-output.

That output is reflects all the missed additions/deletions and will bring this repo and FET in sync, so it's pretty big. Subsequent publishings will only reflect the changes between the last and new versions.

**What else needs doing?**

- [ ] Deleting the [v5.1.1 commit](https://github.com/alphagov/govuk_frontend_toolkit_npm/commit/725df6509f7fcd2eebade32262ec8dd09676b8ff) - as it's not been published to `npm`, and the [publishing script will fail](https://travis-ci.org/alphagov/govuk_frontend_toolkit_npm/builds/202590751) if `package.json` matches `VERSION.txt`

### CODE REVIEW

**Comment by dsingleton** [comment]
The [build is failing](https://travis-ci.org/alphagov/govuk_frontend_toolkit_npm/builds/203738862) due to https://github.com/alphagov/govuk_frontend_toolkit_npm/commit/725df6509f7fcd2eebade32262ec8dd09676b8ff having commited the `package.json` version to `5.1.1`, without publishing to[npmjs.com](https://www.npmjs.com/). So the `"$VERSION_LATEST" != "$VERSION_REGISTRY"` check passes because `$VERSION_REGISTRY` is older than `$VERSION_LATEST`.

As noted above, i think we need to delete that commit, and the next build will be OK and publishing `5.1.1` everywhere. But I'd like to understand how we ended up in a state with the commit on this repo but without the package being updated on npm.

**Comment by gemmaleigh** [comment]
This looks really good, using rsyc in this way is a much cleaner way of preserving deletions - and avoids the need for deletions prior to copying and an additional `git add -u` in a later step (I'd tried this over in #15).

I'm all for tying the two steps together, if we don't remove the step where we are removing the tagged commit - we could set Travis to deploy on a tagged commit - https://docs.travis-ci.com/user/deployment/npm/#What-to-release. 

```
deploy:
  ...
  on:
    tags: true
```

Alternatively, if we'd like to preserve the simplicity of that step (it's much easier to understand now), we could check that the publish step has been successful prior to deploying - and add this as a [condition to to the release](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A).

**Comment by alexmuller** [comment]
I agree that `publish.sh` should only run on the master branch though I don't see how that's caused the state things are currently in. Is the "missing email" output in that Travis output coming from the npm command?

**Comment by dsingleton** [comment]
> I agree that publish.sh should only run on the master branch though I don't see how that's caused the state things are currently in.

I agree thats not the cause here.

That should only cause an issue if upstream changes exist in FET, but haven't been reflected here, which shouldn't happen as the build is triggered immediately on a new release. But, the publish script pulls `master` in, not the latest release. 

I think it would be possible for merged but unreleased changes on FET to be pulled in /  committed on a branch build here, but then not published to `npm` as deploy only happens on master. Getting into a similar situation.

It looks like bit of the travis config intends to limit it to master, but doesn't _seem_ to be working based on this branch?

```yml
branches:
  only:
    - master
```
> Is the "missing email" output in that Travis output coming from the npm command?

I _think_ so, it's not super clear. It looks non-transient, as it's happened on two different builds

@alexmuller could you remind me what the plaintext value of the encoded values look like? And i'll look into the likely npm publishing error

**Comment by dsingleton** [comment]
I [added an npm email](https://github.com/alphagov/govuk_frontend_toolkit_npm/pull/16/commits/37015c65452fa51a8bcfa056e9dcbab2bb8f46df) in a new comment, but but thats not testable until merged to master.

I tried deleting the `v5.1.1` commit* and restarted my branch build - this resulted in the the [build passing initially](https://travis-ci.org/alphagov/govuk_frontend_toolkit_npm/builds/203849448), and skipping the deploy step (as expected).

*This needed a force push on master, not ideal, but it's the best way to test the change here.

> Skipping a deployment with the npm provider because the current build is a pull request.

However, it pushed a _new_ `v5.1.1` commit as part of `publish.sh`, which is running on branches.

**Comment by alexmuller** [comment]
> could you remind me what the plaintext value of the encoded values look like? And i'll look into the likely npm publishing error

I think [you should be able to see that value](https://github.gds/gds/ci-deployment/blob/8ee8aa6665f5e3c02e96366893c5479341c79285/hieradata/env.production.yaml#L88)

**Comment by dsingleton** [comment]
OK. I think this PR is review/mergable It won't immediately fix the problem, but it being on `master` makes it possible to fix from there. As I understand it, the next steps are:

1. Merge this PR, which will prevent the `v5.1.1` from being recreated by any build
2. Remove https://github.com/alphagov/govuk_frontend_toolkit_npm/commit/665364b88f4adf39433ce564f20c29ab7f1d026c from git history and force push master, leaving the commits from this PR in place
3. Master will rebuild automatically and Travis will push a new commit `v5.1.1` commit, and _hopefully_ the addition of an `email` will allow deploying to npm to succeed.

That will get us an accurately up to date repo and and package registry. Where the 2 problems described at the start of the PR are fixed. 

**New problems**

1. Travis is running `publish.sh` on non-`master` branches. Usually this is a no-op as `$VERSION_LATEST` and `$VERSION_REGISTRY` will be in sync. Should `publish.sh` be an explicit deployment task, not a script? Like:
  ```yml
deploy:
  provider: script
  script: publish.sh
  on:
    branch: master
```

  And making `script` a no-op?

2. The execution of `publish.sh` and deployment to npm are not linked. If npm publish fails then the commit will still have been pushed. Previously this was atomic and both actions happened in the same script, `git push` happened only if `npm publish` succeeded. Is it possible to maintain that dependency within the new Travis setup?

  If `publish.sh` becomes a deploy script, thats a step in the right direction, but would still need need to be run before the `npm` deploy, as it sets up files. I'm not sure theres a way of doing this without having _3_ scripts. 1) [setup files](https://github.com/alphagov/govuk_frontend_toolkit_npm/blob/simpler-publish-script/publish.sh#L8-L53), 2) npm deploy, 3) [publish commi](https://github.com/alphagov/govuk_frontend_toolkit_npm/blob/simpler-publish-script/publish.sh#L57-L60).

**Thoughts?**

IMO, in the longer term, the complexity we have to manage here (and upstream), and the time it takes fix when something breaks, is an argument against having  separate repos for different platforms.

For [GOV.UK Frontent](https://github.com/alphagov/govuk_frontend_alpha) we've discussed deployment issues like this and are much more inclined to go the `govuk_template` route, and do all publishing from a central repository.

**Comment by dsingleton** [comment]
For future reference, this was the commit that fixed the publishing problem:

https://github.com/alphagov/govuk_frontend_toolkit_npm/commit/b951cb45230df32e8c91ac51583f1fd831364a62

The problem was that the npm auth token changed between the verison of `npm` used on Jenkins and the one used by Travis. Their docs cover it quite well: https://docs.travis-ci.com/user/deployment/npm/

> For npm version 2+ your api_key can be found in your `~/.npmrc` file. In your `.npmrc` you should see a line similar to `//registry.npmjs.org/:_authToken=YOUR_API_KEY`. A minimal configuration for publishing to npmjs.org with npm version 2+ looks like:
> 
> ```yml
> deploy:
>   provider: npm
>   api_key: "YOUR_API_KEY"
> ```
>
> For npm version ~1 your ~/.npmrc file will look more like:
> 
> ```yml
> _auth=YOUR_API_KEY
> email=YOUR_EMAIL_ADDRESS
> ```

To fix this I ran `npm login` locally, logged in using the account credientials (provided by the GOV.UK Publishing Operations team), copied the api key from `_authToken=YOUR_API_KEY` and encrypted it for Travis with `travis encrypt SECRET_AUTH_TOKEN_VALUE --add deploy.api_key`.

I'm going to open a PR to add more documentation to this repo explaining the travis and ssh setup of this repo, for future maintainers.

**Pull request merged**
